# Generated by Django 4.1 on 2022-11-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patientregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistration',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='dateofbirth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='pannumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='passport',
            field=models.IntegerField(default=0),
        ),
    ]
